POST  https://bx-blue-back-end.herokuapp.com/investor/create
Content-Type: application/json

{
    "name":"Gabriel",
    "password":"123123",
    "email":"gabriel@gmail.com"
}

###
# @name login
POST https://bx-blue-back-end.herokuapp.com/investor/login
Content-Type: application/json

{
    "email":"gabriel@gmail.com",
    "password":"123123"
}

###
# @name registerPokemon
POST https://bx-blue-back-end.herokuapp.com/pokemon/purchase/bulbasaur
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
    "totalPurchase":312.3
}

###
# @name registerPokemon
GET https://bx-blue-back-end.herokuapp.com/pokemon/history
Authorization: {{login.response.body.token}}



